### ISSUE TITLE
Issue with ->having() being used in subqueries.

### ISSUE THREAD

**Issue by StewPoll** [elvanto/picodb#13]
It appears that when you use `->having()` as part of a sub-query, the values of the `aggregatedConditionBuilder` are not pulled from the sub-query, into the parent query.

To replicate this:
```php
<?php

use PicoDb\Database;

# Assuming you have a function that generates a correctly configured `PicoDb\Database` object.
/** @var Database $db */
$db = loadDatabase()

$query = $db->table('users')
    ->isNull('deleted')
    ->eq('activated', true);

$subQuery = $db->table('users_points')
    ->isNull('deleted')
    ->eq('type', 'gameplay')
    ->groupBy('user_id')
    ->having()
    ->gt('SUM(value)', 15)
    ->select('DISTINCT user_id');

echo '<h2>Before inSubquery</h2>';
echo '<pre>' . json_encode([
        'query' => [
            'sql' => $query->buildSelectQuery(),
            'base_values' => $query->getConditionBuilder()->getValues(),
            'aggregated_values' => $query->getAggregatedConditionBuilder()->getValues()
        ],
        'sub_query' => [
            'sql' => $subQuery->buildSelectQuery(),
            'base_values' => $subQuery->getConditionBuilder()->getValues(),
            'aggregated_values' => $subQuery->getAggregatedConditionBuilder()->getValues()
        ]
    ], JSON_PRETTY_PRINT) . '</pre>';
$query->inSubquery('id', $subQuery);
echo "\n";
echo '<h2>After inSubquery</h2>';
echo '<pre>' . json_encode([
        'query' => [
            'sql' => $query->buildSelectQuery(),
            'base_values' => $query->getConditionBuilder()->getValues(),
            'aggregated_values' => $query->getAggregatedConditionBuilder()->getValues()
        ],
        'sub_query' => [
            'sql' => $subQuery->buildSelectQuery(),
            'base_values' => $subQuery->getConditionBuilder()->getValues(),
            'aggregated_values' => $subQuery->getAggregatedConditionBuilder()->getValues()
        ]
    ], JSON_PRETTY_PRINT) . '</pre>';
```

This generates the following outout:
```html

<h2>Before inSubquery</h2><pre>{
    "query": {
        "sql": "SELECT * FROM `users`   WHERE `deleted` IS NULL AND `activated` = ?",
        "base_values": [
            true
        ],
        "aggregated_values": []
    },
    "sub_query": {
        "sql": "SELECT DISTINCT user_id FROM `users_points`   WHERE `deleted` IS NULL AND `type` = ? GROUP BY `user_id`  HAVING `SUM(value)` > ?",
        "base_values": [
            "gameplay"
        ],
        "aggregated_values": [
            15
        ]
    }
}</pre>
<h2>After inSubquery</h2><pre>{
    "query": {
        "sql": "SELECT * FROM `users`   WHERE `deleted` IS NULL AND `activated` = ? AND `id` IN (SELECT DISTINCT user_id FROM `users_points`   WHERE `deleted` IS NULL AND `type` = ? GROUP BY ``user_id``  HAVING `SUM(value)` > ?)",
        "base_values": [
            true,
            "gameplay"
        ],
        "aggregated_values": []
    },
    "sub_query": {
        "sql": "SELECT DISTINCT user_id FROM `users_points`   WHERE `deleted` IS NULL AND `type` = ? GROUP BY ```user_id```  HAVING `SUM(value)` > ?",
        "base_values": [
            "gameplay"
        ],
        "aggregated_values": [
            15
        ]
    }
}</pre>
```

**Comment by beaudurrant** [comment]
Thanks Stewart!

I added ->having() to add basic support in single queries. I’m glad you are using it and have found more use cases.

I don’t think the query you supplied will work with the current version of PicoDB. If you look in BaseConditionBuilder at the function gt($column, $value). The first parameter must be a column name and is escaped, the second parameter is a value. If you wanted to run this query you may need to add additional function similar to gtAggregate($function, $column, $value) or add a variadic function, then validation for the aggregate functions.

The query below will work, but probably not for your test case.

$subQuery = $db->table('users_points')
        ->isNull('deleted')
        ->eq('type', 'gameplay')
        ->groupBy('user_id')
        ->having()
        ->gt('total', 15)
        ->select('SUM(value) as total’);

Also looking at the SQL generated, using GROUP BY in the subquery looks to be escaped multiple times and throws an SQL error (removed having from the subquery).

After those are complete is should be rather easy to copy the values from the subquery (without the condition) for the aggregatedConditionBuilder when a subquery is added to the conditionBuilder.

**Comment by StewPoll** [comment]
Hey @beaudurrant 

The issue with the escaped column name is easy enough to deal with. If there's a space in there it doesn't escape so I can deal with that easily enough.

```php
$subQuery = $db->table('users_points')
    ...
    ->gt('SUM( value )', 15)
```

Not the prettiest of solutions, but it's enough to make it work for now. I hadn't noticed the extra escaping of the `GROUP BY` column until you mentioned it. That does appear to be causing a SQL error as well. I think that should be a seperate issue though.

I only have limited time to work on this myself right now, but I think adding some extra logic to the `__call` function of `Table` should be able to handle this. Something along these lines:

```php
    public function __call($name, array $arguments)
    {
        if ($this->conditionalBuilder === 'HAVING') {
            call_user_func_array(array($this->aggregatedConditionBuilder, $name), $arguments);
        } else {
            if (strpos($name, 'Subquery') !== false) {
                // Something wtih the aggregated condition builder here
            }
            call_user_func_array(array($this->conditionBuilder, $name), $arguments);
        }
        return $this;
    }
```
(I wasn't aware of these functions, but I assume the `lt`/`gt`/`lte`/`gte` functions will need it as well.

**Comment by beaudurrant** [comment]
I think that would be good, then something like:

$this->aggregatedConditionBuilder->addValues(end($arguments)->getAggregatedConditionBuilder()->getValues());

and adding the addValues($values) to the condition builder that will merge the arrays should work.

**Comment by beaudurrant** [comment]
I'm curious about your use case for this. Maybe you can share your query and I can help you out.

Running tests on about 130,000 users and 260,000 points the results are below.

`SELECT * FROM `users`
WHERE `deleted` IS NULL
AND `activated` = true
AND `id` IN (
	SELECT DISTINCT user_id
    FROM `users_points`
    WHERE `deleted` IS NULL
    AND `type` = 'gameplay' 
    GROUP BY `user_id`  
    HAVING SUM(value) > 100
);`

About 1.4 seconds

`SELECT
	`users`.*,
    (
		SELECT SUM(value)
        FROM `users_points`
		WHERE `users_points`.`user_id` = `users`.`id`
        AND `deleted` IS NULL
		AND `type` = 'gameplay' 
    ) AS total
FROM `users`
WHERE `users`.`deleted` IS NULL
AND `users`.`activated` = true
HAVING total > 100`

About 0.01 seconds

**Comment by StewPoll** [comment]
Hmmm - I'll do some tests.

**Comment by beaudurrant** [comment]
I didn't think to add it as I've never used it in a subquery. Should be working now if you wanted to give it a try with the branch =).

**Comment by StewPoll** [comment]
@beaudurrant Ok, after some testing... using the subquery in the SELECT with `HAVING` on the primary query is ~50ms slower than using the subquery in the WHERE.  

The other solution also wouldn't work as I am limited to only getting the one column in this use case for the `SELECT` (`users.id`)

**Comment by beaudurrant** [comment]
https://www.loom.com/share/c91e4e436f7b477ea44a2503e58d4f6c

**Comment by StewPoll** [comment]
@beaudurrant I've taken a look at that fix. 

_Mostly_ it's great. It does indeed solve the issue. However, if you do `->count` before `->findAll` you get the same error. 

At https://github.com/elvanto/picodb/blob/master/lib/PicoDb/Table.php#L313 it does:`$rq = $this->db->execute($this->buildSelectQuery(), array_merge($this->conditionBuilder->getValues(), $this->aggregatedConditionBuilder->getValues()));`

`count` however has this:
```php
        $sql = sprintf(
            'SELECT COUNT(' . $column . ') FROM %s '.implode(' ', $this->joins).$this->conditionBuilder->build().$this->sqlOrder.$this->sqlLimit.$this->sqlOffset,
            $this->db->escapeIdentifier($this->name)
        );

        $rq = $this->db->execute($sql, $this->conditionBuilder->getValues());
```
Potentially this should be:
```php
SELECT COUNT(' . $column . ') FROM %s '.implode(' ', $this->joins).$this->conditionBuilder->build().(empty($this->groupBy) ? '' : 'GROUP BY '.implode(', ', $this->groupBy)).$this->aggregatedConditionBuilder->build().$this->sqlOrder.$this->sqlLimit.$this->sqlOffset,```

This would make it more like the `findAll` command. (And similar for `sum` and other functions?

**Comment by beaudurrant** [comment]
I think that is another issue, if need that use case and want to tackle it at your connivence =). I added what I needed at the time and works for my use cases.

**Comment by beaudurrant** [comment]
I noticed you added parameters to `->count`. This could have also been accomplished using the existing `->distinct` function to set those attributes. =)

**Comment by beaudurrant** [comment]
I'm very busy both personally and professionally. To request new features as issues, for use cases that may or may not exist, and haven't been used the in the previous years of hosting this repos seems a little out of place. I would think it may hinder any users from wanting to contribute in the future if issues are going to be created continually requesting more after their contribution.

**Comment by StewPoll** [comment]
@beaudurrant It's that time of year, we're all busy.

If this gets merged as is, I can get a PR for the other functions. There's a few _other_ things that I plan on getting a PR to help implement too.
