### ISSUE TITLE
composer require elvanto/picodb fail

### ISSUE THREAD

**Issue by fire-ball-wang** [elvanto/picodb#2]
composer require  this package is fail

**Comment by joshmcrae** [comment]
Hi there,

Could you please provide more details? What output do you get when you run `composer require elvanto/picodb`?

The package downloads successfully on our end, without cache.

**Comment by fire-ball-wang** [comment]
I remember you have a package "fguillot/picodb",  why is no-use now ?

**Comment by fire-ball-wang** [comment]
my colleague try to composer require，and he also happen this error

**Comment by joshmcrae** [comment]
There's a stable version on Packagist ([1.0.0](https://packagist.org/packages/elvanto/picodb#1.0.0)) so I'm not sure why Composer wouldn't be able to find this.

Does it help if you add a version number?

`composer require elvanto/picodb ^1.0.0`

**Comment by fire-ball-wang** [comment]
I run the the ```composer require elvalto/picodb ^1.0.0```,  it  happen  this

./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package elvanto/picodb could not be found in any version, there may be a typo in the package name.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.

**Comment by joshmcrae** [comment]
There's a mistake in your first line, the vendor is `elvanto` not `elvalto`.

If the package is already listed in your `composer.json` you can change the version number manually and run `composer install`.

Would you mind sharing the contents of your `composer.json`?

**Comment by fire-ball-wang** [comment]
Hi, this is my composer.json
```
{
    "name": "fire-ball/wx-test",
    "type": "project",
    "description": "A web test system",
    "license": "MIT",
    "config": {
        "preferred-install": "dist",
        "optimize-autoloader": true,
        "discard-changes": true
    },
    "require" : {
        "php" : ">=5.6.0",
        "ext-gd" : "*",
        "ext-mbstring" : "*",
        "ext-hash" : "*",
        "ext-openssl" : "*",
        "ext-json" : "*",
        "ext-ctype" : "*",
        "ext-filter" : "*",
        "ext-session" : "*",
        "pimple/pimple" : "3.0.2",
        "eluceo/ical": "0.10.1",
        "erusev/parsedown" : "1.6.0",
        "fguillot/json-rpc" : "1.2.1",
        "elvanto/picodb":"^1.0.0",
        "elvanto/litemoji": "^1.4"
    },
    "require-dev" : {
        "phpdocumentor/reflection-docblock": "2.0.4",
        "block8/php-docblock-checker": "^1.0",
        "squizlabs/php_codesniffer": "~2.5",
        "symfony/yaml": "2.8.7",
        "symfony/stopwatch" : "2.6.13",
        "phpunit/phpunit" : "4.8.26",
        "friendsofphp/php-cs-fixer": "^2.0"
    },
    "autoload" : {
        "classmap" : ["app/"],
        "psr-4" : {
            "Fireball\\" : "app/"
        },
        "files" : [
            "app/helpers.php"
        ]
    },
    "scripts": {
        "pre-install-cmd": [
            "php -r \"file_exists('.env') || copy('.env.example', '.env');\""
        ],
        "post-install-cmd": [
        ],
        "post-update-cmd": [
        ]
    }
}
```
the  ```elvanto/litemoji``` is success, but the ``elvanto/picodb` is show  this ``` The requested package elvanto/picodb could not be found in any version, there may be a typo in the package name.```

**Comment by joshmcrae** [comment]
Using your `composer.json` I can successfully install all of the packages.

Are you using a third-party mirror of Packagist, like https://pkg.phpcomposer.com? We created the package about 3 days ago so it's likely that some mirrors might not have the data yet.

**Comment by fire-ball-wang** [comment]
oh, I rembember I use a third-party mirror yesterday，maybe that's the reason.  
thank you for your help.
