### ISSUE TITLE
Using OFFSET with Microsoft SQL Server produces syntax error

### ISSUE THREAD

**Issue by Mr-Kaos** [elvanto/picodb#24]
Using the `Table->offset()` function produces a syntax error when used with the MSSQL driver.

Currently all database drivers use the same `OFFSET` clause.
The OFFSET clause is different in SQL Server to the other database engines.

If using the MSSQL driver, the offset statement in a query should look like `SELECT x FROM table OFFSET n ROWS FETCH NEXT n ROWS ONLY`. `SELECT TOP(x)` is not used with T-SQL statements.

**Comment by joshmcrae** [comment]
Hi @Mr-Kaos, I've opened a branch called [mssql-offset-limit](https://github.com/elvanto/picodb/blob/mssql-offset-limit/lib/PicoDb/Driver/Mssql.php#L186) which can be installed via composer using [dev-mssql-offset-limit](https://packagist.org/packages/elvanto/picodb#dev-mssql-offset-limit) as the package version. Would you mind testing this and letting me know if it solves your issue?

If I'm understanding correctly, the `OFFSET n ROWS` and `FETCH NEXT n ROWS ONLY` parts of the clause can be used independently. This is how I've approached the SQL generation.

**Comment by Mr-Kaos** [comment]
Hi @joshmcrae, I have tested the branch and encountered the following error:
`Declaration of PicoDb\Driver\Mssql::getLimitClause($limit, int $offset) must be compatible with PicoDb\Driver\Base::getLimitClause($limit, $offset)`.
I believe this is just due to the base declaration missing "`int`" in its definition.

I also overlooked the fact that in T-SQL, an `ORDER BY` clause is required for an offset clause. Apologies that I did not mention that in my first comment.
I'm not sure if this means that the `getLimitClause()` function needs to support a column name to allow for the order by clause, or if the developer needs to use the `orderBy()` function beforehand to achieve this functionality.

**Comment by joshmcrae** [comment]
@Mr-Kaos I've just pushed a change to correct the signature of `PicoDb\Driver\Mssql::getLimitClause()`. You may need to clear Composer caches in order to pull the development branch again.

We'll leave it up to the developer to make use of `orderBy()` when using `limit()` and `offset()`. This keeps the API generic enough to make sense for the other database drivers.

**Comment by Mr-Kaos** [comment]
@joshmcrae Thanks, I pulled the changes and it works perfectly, but only if the `orderBy()` and `offset()` functions are used on the table object to build the query. If these are omitted, an error is returned and the query fails. This means that all queries that utilise the `getLimitClause()` function must use both the `orderBy()` and `offset()` functions.

Not sure if that is worth the hassle to implement given that no other drivers seem to require this when running SELECT queries.

I also found another bug with the `getSchemaVersion()` function in the Mssql driver class, where the "CREATE TABLE IF NOT EXISTS" is found to be invalid. Should I open this as a new issue as well?

**Comment by joshmcrae** [comment]
@Mr-Kaos This is one of those areas where we have to strike a balance between the library providing a generic abstraction over all relational database systems and having an API that ensures only valid queries can be constructed. In this instance, we'll have to rely upon clients making use of MSSQL to call both `->orderBy()` **and** `->offset()`/`->limit()` when using offset or limit.

> I also found another bug with the getSchemaVersion() function in the Mssql driver class, where the "CREATE TABLE IF NOT EXISTS" is found to be invalid. Should I open this as a new issue as well?

A separate issue would ensure we can get the existing changes out in a timely manner. We welcome PRs if you have a solution for this already.

**Comment by joshmcrae** [comment]
@Mr-Kaos The changes supporting MSSQL are now available through release [4.4.0](https://github.com/elvanto/picodb/releases/tag/4.4.0).
